# Site settings
title: 'Ed Charbeneau'
email: ed.Charbeneau@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles about software development, HTML5, C#, and  ASP.NET, .NET Core.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://edcharbeneau.com" # the base hostname & protocol for your site
twitter_username: edcharbeneau
github_username:  edcharbeneau
exclude: ['node_modules']
paginate: 10
paginate_path: "/page:num/"
permalink: /:year/:month/:title
sass:
  compressed: true

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate, github-pages]

collections:
  sessions:
    output: true

defaults:
  -
    scope:
      type: "sessions"
    values:
      layout: "session"
      date: "2016-08-01"